name: pebblenote
description: A minimal, modern note-taking app with reminders, checklists, and clean UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Utils
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  share_plus: ^7.2.1
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  
  # UI
  flutter_staggered_grid_view: ^0.7.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  
  # Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/icon/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#4A90E2"
    theme_color: "#4A90E2"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48